# -*- coding: utf-8 -*-
"""Text-to-Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DR32-94vxd6b6NlQUJl0kWC2lK9cSVJ1
"""

!nvidia-smi

!pip install transformers diffusers accelerate

!pip show torch

from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt
import torch

model_id="dreamlike-art/dreamlike-diffusion-1.0"

pipe=pipe.to("cuda")

prompt="dreamlikeart, a grungy woman with rainbow hair, travelling between dimensions, dynamic pose, happy, soft eyes and narrow chin, extreme bokeh, dainty figure, long hair straight down, torn kawaii shirt and baggy jeans, In style of by Jordan Grimmer and greg rutkowski, crisp lines and color, complex background, particles, lines, wind, concept art, sharp focus, vivid colors"

image=pipe(prompt).images[0]

image

def generate_image(pipe, prompt, params):
  img = pipe(prompt, **params).images

  num_images = len(img)

  if(num_images>1):
    fig, ax = plt.subplots(nrows = 1, ncols= num_images)

    for i in range(num_images):
      ax[i].imshow(img[i])
      ax[i].axis("off")

  else:
    fig = plt.figure()
    plt.imshow(img[0])
    plt.axis('off')

  plt.tight_layout()

prompt="A blue future-like dream bike with multiple features, soft colors, 3d, highly polished"

params={}

generate_image(pipe,prompt,params)

params = {'num_inference_steps': 100}
generate_image(pipe,prompt,params)

